all: draft-privacy-pass draft-davidson-pp-protocol

.PHONY: draft-privacy-pass draft-davidson-pp-protocol
draft-privacy-pass:
	cd OLD-draft-privacy-pass && make
draft-davidson-pp-protocol:
	cd draft-davidson-pp-protocol && make