all: draft-davidson-pp-protocol draft-davidson-pp-architecture draft-svaldez-pp-http-api

.PHONY: draft-davidson-pp-protocol draft-davidson-pp-architecture draft-svaldez-pp-http-api

draft-privacy-pass:
	cd OLD-draft-privacy-pass && make
draft-davidson-pp-protocol:
	cd draft-davidson-pp-protocol && make
draft-davidson-pp-architecture:
	cd draft-davidson-pp-architecture && make
draft-svaldez-pp-http-api:
	cd draft-svaldez-pp-http-api && make