all: draft-privacy-pass draft-davidson-pp-protocol draft-davidson-pp-architecture

.PHONY: draft-privacy-pass draft-davidson-pp-protocol draft-davidson-pp-architecture
draft-privacy-pass:
	cd OLD-draft-privacy-pass && make
draft-davidson-pp-protocol:
	cd draft-davidson-pp-protocol && make
draft-davidson-pp-architecture:
	cd draft-davidson-pp-architecture && make